# Generated by Django 2.2.4 on 2019-09-08 05:17

import book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('author_name', models.CharField(max_length=32, verbose_name='作者')),
                ('author_age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
            ],
            options={
                'verbose_name_plural': '作者',
                'db_table': 'CX_Author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('book_title', models.CharField(max_length=64, verbose_name='书名')),
                ('book_cover', models.ImageField(blank=True, default='book_cover/默认封面.jpg', null=True, upload_to='book_cover/', verbose_name='书籍封面')),
                ('price', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='售价')),
                ('is_free', models.BooleanField(default=False, verbose_name='限时免费')),
                ('book_brief', models.TextField(blank=True, default='小说为c享用户自主上传,没有简介', null=True, verbose_name='简介')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('book_preview', models.TextField(blank=True, null=True, verbose_name='书籍导读')),
                ('book_audio', models.FileField(blank=True, null=True, upload_to='book_audio/', verbose_name='书籍音频')),
                ('book_video', models.FileField(blank=True, null=True, upload_to='book_video/', verbose_name='书籍视频')),
                ('author', models.ManyToManyField(to='book.Author')),
            ],
            options={
                'verbose_name_plural': '图书',
                'db_table': 'CX_Book',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('category_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '书籍分类',
                'db_table': 'CX_BookCategory',
            },
        ),
        migrations.CreateModel(
            name='BookRack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='加入书架时间')),
            ],
            options={
                'verbose_name_plural': '书架',
                'db_table': 'CX_BookRack',
            },
        ),
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('section', models.CharField(max_length=256, verbose_name='章节名')),
                ('section_content', models.FileField(blank=True, null=True, upload_to=book.models.get_file_path)),
                ('word_number', models.IntegerField(blank=True, null=True, verbose_name='章节字数')),
                ('book', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='book.Book', verbose_name='所属书名')),
            ],
            options={
                'verbose_name_plural': '章节',
                'db_table': 'CX_BookContent',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='books', to='book.BookCategory'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_rack',
            field=models.ManyToManyField(blank=True, related_name='book', to='book.BookRack'),
        ),
    ]
