# Generated by Django 2.2.4 on 2019-09-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ballot',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='得票'),
        ),
    ]
