# Generated by Django 2.2.4 on 2019-09-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_ballot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontent',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
    ]
